flash camera + play animation events
FNF-CNE-Devs/CodenameEngine pull request #199
Opened 2023-08-21 15:13 UTC by SwickTheGreat

add 2 basic events that might help some people out. both are made by lunarcleint and not by me. i just hardcoded them in. icons are not included. let me know if there are any issues.

2023-08-21 20:05 UTC, lunarcleint requested changes

2023-08-21 20:05 UTC, lunarcleint commented on source/funkin/backend/chart/Chart.hx
> +					4 => "Flash Camera",
you dont need to add this since old cne charts didnt have these

2023-08-21 20:05 UTC, lunarcleint commented on source/funkin/game/PlayState.hx
> +				Reflect.getProperty(this, event.params[2]).flash(event.params[0], event.params[1], null, true);
should use a tereny statement instead of reflect here

2023-08-23 02:08 UTC, lunarcleint commented
we need icons now, the cam flash one would be easy but im not sure about play anim

2023-08-23 12:26 UTC, SwickTheGreat commented
> we need icons now, the cam flash one would be easy but im not sure about play anim

i cannot draw for the life of me

2023-08-23 21:41 UTC, biomseed commented
![image](https://github.com/FNF-CNE-Devs/CodenameEngine/assets/73907153/bf6f522d-a9be-4474-96ef-2e5677277787)
play anim

2024-02-03 01:51 UTC, lunarcleint commented
Already added in dev repo, coming soon. Thanks for your time commiting to cne tho :)

2024-02-03 01:51 UTC, closed without merging