Fixed Window dark mode issue for Windows 10 users!
FNF-CNE-Devs/CodenameEngine pull request #449
Opened 2024-11-20 10:43 UTC by TBar09

-Added a fix for Windows 10 users where they would have to unfocus and refocus the application to set the window to dark mode.
-Added `setWindowBorderColor`, which can set the window header (and/or border) to any color.

2024-11-20 12:47 UTC, NeeEoo requested changes

2024-11-20 22:16 UTC, TBar09 commented on source/funkin/backend/utils/NativeAPI.hx
> +		#end
I tried using UpdateWindow and it unfortunately doesn't work. As far as I know, this is the best way to do it that doesn't make anything look too out-of-place, like using ShowWindow.

I will fix some of the issues mentioned though.

2024-11-22 00:49 UTC, NeeEoo commented
@TBar09 Please review the changes i pushed, are you okay with them?

2024-11-22 04:39 UTC, TBar09 commented
I am fine with the changes. They are a good addition 👍

2024-11-23 07:34 UTC, TBar09 reviewed
Looks good to me 👍

2024-11-26 23:27 UTC, NexIsDumb commented
opa

2024-11-26 23:30 UTC, merged